# This config is for a large set of stylistic rules useful for lint highlighting.
# This ruleset is not used in CI as it would be too strict.

parser: babel-eslint
extends: airbnb
root: true
rules:
  import/no-extraneous-dependencies: [2, {}]
  react/jsx-filename-extension: [0]
  max-len: [2, { "code": 120, "ignoreComments": true }]
